#!/usr/bin/env python3
"""Generate supabase/seed_okr.sql from the authoritative workbook extract
scripts/pilot/la_okr_2026Q3.json (IPPDD_OKR_Q3_2026-08-01_v1.0).

Deterministic UUIDs (uuid5 over stable keys) keep the seed idempotent-by-content
and let the importer detect duplicates. Nothing here is invented: titles,
weights, deadlines and measurement text come from the workbook.
"""
import json
import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = json.loads((ROOT / "scripts/pilot/la_okr_2026Q3.json").read_text())

NS = uuid.UUID("6ba7b810-9dad-11d1-80b4-00c04fd430c8")
EMP_LA = "e0000000-0000-4000-8000-000000000002"
EMP_DIRECTOR = "e0000000-0000-4000-8000-000000000001"
EMP_REVIEWER = "e0000000-0000-4000-8000-000000000003"
DEPT_IPPDD = "d0000000-0000-4000-8000-000000000001"
QUARTER = "a0000000-0000-4000-8000-000000000001"


def q(s):
    if s is None:
        return "null"
    return "'" + str(s).replace("'", "''") + "'"


def pct(s):
    return float(s.rstrip("%"))


def oid(code):
    return str(uuid.uuid5(NS, f"okr:2026Q3:LA:{code}"))


def krid(ocode, kcode):
    return str(uuid.uuid5(NS, f"okr:2026Q3:LA:{ocode}:{kcode}"))


def target_from_title(title):
    m = re.search(r"\[([^\]]+)\]", title)
    return m.group(1) if m else None


lines = [
    "-- GENERATED by scripts/pilot/gen_seed_okr.py from scripts/pilot/la_okr_2026Q3.json",
    "-- Source of truth: Drive workbook IPPDD_OKR_Q3_2026-08-01_v1.0 (LA manager section).",
    "-- Regenerate instead of editing by hand.",
    "begin;",
]

for o in DATA["objectives"]:
    lines.append(
        "insert into objectives (id, employee_id, quarter_id, objective_code, title, weight, status)\n"
        f"values ({q(oid(o['code']))}, {q(EMP_LA)}, {q(QUARTER)}, {q(o['code'])}, "
        f"{q(o['title'])}, {pct(o['weight'])}, 'ACTIVE');"
    )
    for k in o["krs"]:
        target = target_from_title(k["title"])
        lines.append(
            "insert into key_results (id, objective_id, kr_code, title, description, weight,\n"
            "  target_description, measurement_method, deadline, status)\n"
            f"values ({q(krid(o['code'], k['code']))}, {q(oid(o['code']))}, {q(k['code'])}, "
            f"{q(k['title'])}, {q(k.get('description'))}, {pct(k['weight'])},\n"
            f"  {q(target)}, {q(k.get('measurement'))}, {q(k.get('deadline'))}, 'NOT_STARTED');"
        )

# --- Pilot work items grounded in the workbook KR scope -----------------------
WI = [
    dict(
        code="IPPDD-2026Q3-W001", kr=("O1", "KR1"), type="PROCESS", prio="CRITICAL",
        title="Данс нээлтийн end-to-end процессын нэгдсэн стандарт багц (5 бүрэлдэхүүн)",
        dod="Process map, дүрэм, журам, RACI, control checklist — 5 бүрэлдэхүүн бүгд боловсрогдож, "
            "ХОБПХГ-ийн газрын захирлаар хянагдаж батлагдсан байна (Documentation Readiness 5/5).",
        deadline="2026-08-24", status="IN_PROGRESS",
        reqs=["Process Map", "Дүрэм", "Журам", "RACI", "Control Checklist"],
    ),
    dict(
        code="IPPDD-2026Q3-W002", kr=("O2", "KR1"), type="STANDARD", prio="HIGH",
        title="Харилцагчийн бэлгийн зарцуулалтын нотлох баримтын 3 баримт (checklist + стандарт + журам)",
        dod="3 баримт бүгд боловсрогдож, ХОБПХГ-ийн газрын захирлаар хянагдаж батлагдсан байна.",
        deadline="2026-08-23", status="IN_PROGRESS",
        reqs=["Checklist", "Стандарт", "Журам"],
    ),
    dict(
        code="IPPDD-2026Q3-W003", kr=("O2", "KR2"), type="AI_AGENT", prio="HIGH",
        title="Claude автоматжуулалт — бэлгийн хяналтын 1 domain (coverage ≥80%)",
        dod="Сонгосон domain-д автоматжуулалтын process coverage ≥80%, тест давсан, хүний acceptance "
            "болон deployment/use evidence бүрдсэн байна.",
        deadline="2026-09-06", status="IN_PROGRESS", impl=True, valid=True,
        reqs=["Hypothesis / experiment design", "Test case багц", "Pilot тайлан"],
        metric=("Process Coverage", "GTE", 80, "%"),
    ),
    dict(
        code="IPPDD-2026Q3-W004", kr=("O3", "KR4"), type="TRAINING", prio="MEDIUM",
        title="Claude сургалт — харьяа нэгжийн ажилтнуудын хамрагдалт ≥95%",
        dod="Нийт ажилтны ≥95% сургалтад хамрагдаж дуусгасан, хамрагдалтын тайлан захирлаар хянагдсан.",
        deadline="2026-09-30", status="IN_PROGRESS", valid=True,
        reqs=["Сургалтын хөтөлбөр", "Хамрагдалтын тайлан"],
        metric=("Training Completion Rate", "GTE", 95, "%"),
    ),
    dict(
        code="IPPDD-2026Q3-W005", kr=("O1", "KR2"), type="KPI", prio="MEDIUM",
        title="Weekly CPI review cadence — 13 хуралдааны гүйцэтгэл",
        dod="Q3-ийн 13 weekly CPI review бүгд явагдаж, процесс тус бүрийн ≥5 KPI метрик хэмжигдсэн.",
        deadline="2026-09-16", status="IN_PROGRESS", valid=True,
        reqs=["CPI review хуваарь ба агенда", "KPI Dashboard загвар"],
        metric=("CPI Review Completion", "GTE", 13, "хуралдаан"),
    ),
]

for w in WI:
    wid = str(uuid.uuid5(NS, f"work:{w['code']}"))
    kr = krid(*w["kr"])
    lines.append(
        "insert into work_items (id, key_result_id, owner_id, department_id, quarter_id, work_code,\n"
        "  title, work_type, priority, definition_of_done, deadline, status, reviewer_id, approver_id,\n"
        "  implementation_required, validation_required, created_by)\n"
        f"values ({q(wid)}, {q(kr)}, {q(EMP_LA)}, {q(DEPT_IPPDD)}, {q(QUARTER)}, {q(w['code'])},\n"
        f"  {q(w['title'])}, '{w['type']}', '{w['prio']}', {q(w['dod'])}, {q(w['deadline'])}, "
        f"'{w['status']}', {q(EMP_REVIEWER)}, {q(EMP_DIRECTOR)},\n"
        f"  {str(w.get('impl', False)).lower()}, {str(w.get('valid', False)).lower()}, {q(EMP_LA)});"
    )
    for i, r in enumerate(w["reqs"], start=1):
        rid = str(uuid.uuid5(NS, f"req:{w['code']}:{r}"))
        lines.append(
            "insert into deliverable_requirements (id, work_item_id, name, required, sequence)\n"
            f"values ({q(rid)}, {q(wid)}, {q(r)}, true, {i});"
        )
    if "metric" in w:
        name, op, val, unit = w["metric"]
        mid = str(uuid.uuid5(NS, f"metric:{w['code']}"))
        lines.append(
            "insert into metric_validations (id, key_result_id, work_item_id, metric_name,\n"
            "  target_operator, target_value, unit, validation_status)\n"
            f"values ({q(mid)}, {q(kr)}, {q(wid)}, {q(name)}, '{op}', {val}, {q(unit)}, 'PENDING');"
        )

# KRs with active work start IN_PROGRESS
active = {krid(*w["kr"]) for w in WI}
for k in sorted(active):
    lines.append(f"update key_results set status = 'IN_PROGRESS' where id = {q(k)};")

lines.append("commit;")
out = ROOT / "supabase/seed_okr.sql"
out.write_text("\n\n".join(lines) + "\n")
print(f"wrote {out} ({len(lines)} statements)")
