-- GENERATED by scripts/pilot/gen_seed_okr.py from scripts/pilot/la_okr_2026Q3.json

-- Source of truth: Drive workbook IPPDD_OKR_Q3_2026-08-01_v1.0 (LA manager section).

-- Regenerate instead of editing by hand.

begin;

insert into objectives (id, employee_id, quarter_id, objective_code, title, weight, status)
values ('ac6ae364-e549-572f-8788-0b6316945a34', 'e0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001', 'O1', 'Эх үүсвэрийн данс нээлт болон уулзалтын процессын нэгдсэн стандарт, тодорхой эзэмшигч, хяналтын цэгтэйгээр ISCMD-д хэрэгжих бэлэн байдал хангагдана.', 40.0, 'ACTIVE');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('f8a9166f-cb3b-5668-a310-056b749d77ef', 'ac6ae364-e549-572f-8788-0b6316945a34', 'KR1', 'Данс нээлтийн end-to-end процессын нэгдсэн стандарт багцын (process map, дүрэм, журам, RACI, control checklist) 5 бүрэлдэхүүний ХОБПХГазрын захирлаар хянуулж батлуулах бэлэн байдлыг \[0%→100%\] болгож 2026-08-24-ны дотор хангана.', 'Данс нээлтийн end-to-end as-is/to-be зураглалд тулгуурлан process map, дүрэм, журам, RACI, control checklist гэсэн 5 бүрэлдэхүүнийг боловсруулж, ХОБХУГ, СТНУШГ болон ХАГ-тай review хийлгэнэ. Review-ийн тайлбарыг тусган нэгдсэн стандарт багцын драфт гаргаж, ХОБХУГ-ийн захиралд ахин хянуулна. Эцсийн хувилбарыг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгнө.  Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш): • ХОБХУГ хүлээн авалтын тэмдэглэл: байна • 5 бүрэлдэхүүн бүрийн бэлэн байдал: 100%', 40.0,
  '0%→100%\', 'Биелсэн гэж үзэх нөхцөл: Данс нээлтийн end-to-end процессын нэгдсэн стандарт багцын 5 бүрэлдэхүүн (process map, дүрэм, журам, RACI, control checklist) бүгд боловсрогдож, ХОБПХГ-ийн газрын захирлаар хянагдаж батлагдсан байна.  Тооцох аргачлал: Томьёо: Documentation Readiness Rate = (Захирлаар хянагдаж батлагдсан бүрэлдэхүүний тоо / 5) × 100%  Шаталсан үнэлгээ: 100%: 5/5 бүрэлдэхүүн хянагдаж батлагдсан. 50%: 3/5 бүрэлдэхүүн хянагдсан. 0%: 2 буюу түүнээс цөөн бүрэлдэхүүн хянагдсан, эсвэл evidence дутуу.  Evidence: DOC-0035 Policy & Standard & Procedure Set; DOC-0070 Registers & Logs', '2026-08-24', 'NOT_STARTED');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('329690bb-2c3a-5edd-a49c-855ccc95d788', 'ac6ae364-e549-572f-8788-0b6316945a34', 'KR2', 'Нэвтэрсэн стандартчилсан процессуудын KPI Dashboard дахь weekly CPI review cadence-ийн гүйцэтгэлийг \[0%→100%\] болгож 2026-09-16-ны дотор хангана.', 'Нэвтэрсэн стандартчилсан процесс тус бүрийн KPI (cycle time, алдаа, STP, SLA, adoption)-ийн хэмжилтийн аргачлал болон weekly CPI review-ийн хуваарь, агендыг боловсруулж, ХОБХУГ болон СТНУШГ-тай review хийлгэнэ. Review-ийн тайлбарыг тусган CPI review-ийн драфт хуваарь болон KPI Dashboard загвар гаргаж, ХОБХУГ-ийн захиралд ахин хянуулна. Батлагдсан CPI review framework-ийг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгч, Q3-ийн туршид тогтмол weekly review-г явуулна.  Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш): • Хэмжих KPI метрик тоо: ≥5 (cycle time, алдаа, STP, SLA, adoption) • Dashboard шинэчлэлт давтамж: долоо хоног тутам', 30.0,
  '0%→100%\', 'Биелсэн гэж үзэх нөхцөл: Q3-ийн туршид товлогдсон weekly CPI review (13 хуралдаан)-ийн 100%-ийг гүйцэтгэсэн, нэвтэрсэн процесс тус бүрийн доод тал нь 5 KPI метрик хэмжигдсэн байна.  Тооцох аргачлал: Томьёо: CPI Review Completion Rate = (Явуулсан CPI review тоо / 13) × 100%  Шаталсан үнэлгээ: 100%: 13/13 хуралдаан явагдсан. 50%: 7–12/13 хуралдаан явагдсан. 0%: 6 буюу түүнээс цөөн хуралдаан явагдсан, эсвэл evidence дутуу.  Evidence: DOC-0103 Management Pack; DOC-0070 Registers & Logs; CPI review attendance log', '2026-09-16', 'NOT_STARTED');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('bf79d15b-ca44-54ee-a628-9ab22978f2b0', 'ac6ae364-e549-572f-8788-0b6316945a34', 'KR3', 'Q2 backlog-оос сонгосон 3 процессын сайжруулалтыг ХОБПХГазрын захирлаар баталгаажуулж, UAT орчинд шалгаж, production-д live болсон тоог \[0/3→3/3\] болгож 2026-09-23-ны дотор хангана.', 'Q2 backlog-оос сонгосон 3 процессын сайжруулалт бүрийн UAT test plan болон acceptance criteria-г боловсруулж, МТҮААГ болон ХОБХУГ-тай review хийлгэнэ. UAT туршилтын дүнд тулгуурлан production deployment-д зориулсан Change Request болон acceptance тайлангийн драфт гаргаж, CFT lead болон ХОБХУГ-ийн захиралд ахин хянуулна. Acceptance gate-ийг давсан 3 сайжруулалтыг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгч, production deployment-ийг гүйцэтгэнэ.  Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш): • UAT defect closure: 100% • CFT lead acceptance: 3/3 • ISCMD acceptance: 3/3', 30.0,
  '0/3→3/3\', 'Биелсэн гэж үзэх нөхцөл: Q2 backlog-оос сонгосон 3 процессын сайжруулалт бүр UAT болон ISCMD acceptance gate-ийг давж, production-д live болж, ХОБПХГ-ийн газрын захирлаар баталгаажсан байна.  Тооцох аргачлал: Томьёо: Live Deployment Rate = (Production-д live болсон сайжруулалтын тоо / 3) × 100%  Шаталсан үнэлгээ: 100%: 3/3 сайжруулалт production-д live болсон. 50%: 2/3 сайжруулалт live болсон. 0%: 1 буюу нэг ч сайжруулалт live болоогүй.  Evidence: DOC-0146 PRD/BRD & Requirements Traceability; DOC-0070 Registers & Logs; UAT sign-off болон production deployment log', '2026-09-23', 'NOT_STARTED');

insert into objectives (id, employee_id, quarter_id, objective_code, title, weight, status)
values ('8f99546a-e034-56f1-b560-def907307a18', 'e0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001', 'O2', 'Хариуцсан процесс, бэлгийн хяналтыг сайжруулж автоматжуулна.', 40.0, 'ACTIVE');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('2de7ea1d-c703-5315-be44-b77f73d104d7', '8f99546a-e034-56f1-b560-def907307a18', 'KR1', 'Харилцагчийн (гарын) бэлгийн зарцуулалтын нотлох баримт бүрдүүлэлтийн 3 баримт (checklist + стандарт + журам)-ын ХОБПХГазрын захирлаар хянуулж батлуулах бэлэн байдлыг \[0%→100%\] болгож 2026-08-23-ны дотор хангана.', 'Харилцагчийн (гарын) бэлгийн зарцуулалтад тавигдах хуулийн болон дотоод дүрмийн шаардлагад тулгуурлан checklist, стандарт болон журам гэсэн 3 баримт бичгийг боловсруулж, ХОБХУГ болон ХАГ-тай review хийлгэнэ. Review-ийн тайлбарыг тусган 3 баримт бичгийн нэгдсэн драфт гаргаж, ХАГ болон ХОБХУГ-ийн захиралд ахин хянуулна. Эцсийн 3 баримт бичгийг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгнө.  Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш): • ХАГ-ийн compliance review тэмдэглэл: байна • ХОБХУГ-ийн хүлээн авалт: баталгаажсан', 40.0,
  '0%→100%\', 'Биелсэн гэж үзэх нөхцөл: Харилцагчийн бэлгийн зарцуулалтын нотлох баримт бүрдүүлэлтийн 3 баримт (checklist + стандарт + журам) бүгд боловсрогдож, ХОБПХГ-ийн газрын захирлаар хянагдаж батлагдсан байна.  Тооцох аргачлал: Томьёо: Document Readiness Rate = (Захирлаар батлагдсан баримт бичгийн тоо / 3) × 100%  Шаталсан үнэлгээ: 100%: 3/3 баримт хянагдаж батлагдсан. 50%: 2/3 баримт хянагдсан. 0%: 1 буюу нэг ч баримт батлагдаагүй, эсвэл evidence дутуу.  Evidence: DOC-0035 Policy & Standard & Procedure Set; DOC-0070 Registers & Logs', '2026-08-23', 'NOT_STARTED');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('8bc1ffe8-d36d-5bed-b794-97b5f0fed5a8', '8f99546a-e034-56f1-b560-def907307a18', 'KR2', 'Харилцагчийн бэлгийн хяналтын 1 domain-д Claude автоматжуулалтын process coverage-ийг \[0%→≥80%\] болгож 2026-09-06-ны дотор хангана.', 'Харилцагчийн бэлгийн хяналтын автоматжуулах 1 domain-ийг тодорхойлж, Claude-аар хэрэгжүүлэх hypothesis болон experiment design, test case-ийг боловсруулж, ХОБХУГ болон ХАГ-тай review хийлгэнэ. Review-ийн тайлбарыг тусган pilot автоматжуулалтын драфт тайлан болон coverage хэмжих аргачлал гаргаж, ХОБХУГ-ийн захиралд ахин хянуулна. Баталгаажсан автоматжуулалтын тайлан болон хэрэгжилтийн баримтыг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгнө.  Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш): • Туршилтын hypothesis тайлан: байна • False positive rate: ≤5%', 30.0,
  '0%→≥80%\', 'Биелсэн гэж үзэх нөхцөл: Харилцагчийн бэлгийн хяналтын сонгосон 1 domain-д Claude автоматжуулалтын process coverage ≥80%-д хүрсэн, ХОБПХГ-ийн газрын захирлаар хянагдсан байна.  Тооцох аргачлал: Томьёо: Process Coverage = (Автоматжуулсан check хийгдсэн transaction / Нийт domain transaction) × 100%  Шаталсан үнэлгээ: 100%: Coverage ≥80% хүрсэн. 50%: Coverage 40%–79%. 0%: Coverage 40%-аас доош, эсвэл туршилт эхлэгдээгүй.  Evidence: DOC-0117 Experiment Registry; DOC-0070 Registers & Logs; Claude automation test log', '2026-09-06', 'NOT_STARTED');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('bc2495ef-1098-5420-807d-eb7f41b2ac1d', '8f99546a-e034-56f1-b560-def907307a18', 'KR3', 'Төв болон салбарын борлуулалт дэмжлэгийн стандарт + template-ийн ISCMD Pilot Acceptance Gate-ийн бэлэн байдлыг \[0%→100% (PASS)\] болгож 2026-09-08-ны дотор хангана.', 'Төв болон салбарын борлуулалт дэмжлэгийн стандарт болон template-ийн агуулга, бүтцийг боловсруулж, ХОБХУГ болон ССУГ-тай review хийлгэнэ. Review-ийн тайлбарыг тусган pilot cycle-д ашиглах стандарт болон template-ийн драфт гаргаж, ХОБХУГ-ийн захиралд (ISCMD Pilot Acceptance Gate) ахин хянуулна. Acceptance Gate-ийг давсан стандарт болон template-ийг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгнө.  Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш): • Pilot cycle дахь template ашиглалт: ≥5 удаа • ССУГ хүлээн авалт: баталгаажсан', 30.0,
  '0%→100% (PASS)\', 'Биелсэн гэж үзэх нөхцөл: Борлуулалт дэмжлэгийн стандарт болон template 1 pilot cycle-ийг гүйцэтгэж, ISCMD Pilot Acceptance Gate PASS баталгаажсан байна.  Тооцох аргачлал: Томьёо: Gate Result — PASS = 100%, FAIL = 0%  Шаталсан үнэлгээ: 100%: Pilot cycle дуусч ISCMD Pilot Acceptance Gate PASS авсан. 50%: Pilot cycle гүйцэтгэгдсэн боловч Gate review хүлээгдэж байгаа. 0%: Pilot cycle дуусгаагүй эсвэл Gate FAIL.  Evidence: DOC-0035 Policy & Standard & Procedure Set; DOC-0070 Registers & Logs; ISCMD Pilot Acceptance Gate sign-off', '2026-09-08', 'NOT_STARTED');

insert into objectives (id, employee_id, quarter_id, objective_code, title, weight, status)
values ('7fdf8f6f-00f4-523c-8501-f9f88ceae74d', 'e0000000-0000-4000-8000-000000000002', 'a0000000-0000-4000-8000-000000000001', 'O3', 'O3: Хариуцсан тайлан, өөрчлөлт болон C-Level эвентийн засаглалыг хангана.', 20.0, 'ACTIVE');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('49d75f84-ede4-52a8-bb5e-aea1b8e0eb7f', '7fdf8f6f-00f4-523c-8501-f9f88ceae74d', 'KR1', 'Хариуцсан тайлангуудын Report Inventory register болон reports.netcapital.mn дахь report↔document readiness-ийг \[0%→100%\] болгож 2026-09-21-ны дотор хангана.', 'Хариуцсан тайлангуудын жагсаалт, эх сурвалж, owner болон давтамжийн мэдээллийг боловсруулж, СГУГ-тай review хийлгэнэ. Review-ийн тайлбарыг тусган Report Inventory register болон reports.netcapital.mn нийтлэлд зориулсан тайлан бүрийн мета өгөгдлийн драфт гаргаж, СГУГ-д ахин хянуулна. Эцсийн бүртгэлт болон нийтлэлийг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгнө.    Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш):  • Тайлан бүрийн эх сурвалж баталгаажилт: 100%  • reports.netcapital.mn нийтлэлт: 100%', 30.0,
  '0%→100%\', 'Биелсэн гэж үзэх нөхцөл:  Хариуцсан бүх тайлан Report Inventory register-т эх сурвалж тулгагдаж бүртгэгдсэн, reports.netcapital.mn-д нийтлэгдсэн, ХОБПХГ-ийн газрын захирлаар хянагдсан байна.    Тооцох аргачлал:  Томьёо: Report Readiness Rate = (Бүртгэгдэж нийтлэгдсэн тайлангийн тоо / Нийт хариуцах тайлангийн тоо) × 100%    Шаталсан үнэлгээ:  100%: Бүх хариуцсан тайлан бүртгэгдэж нийтлэгдсэн.  50%: 50%–99% тайлан бэлэн байдал хангагдсан.  0%: 50%-аас доош тайлан бэлэн байдал хангагдсан, эсвэл evidence дутуу.    Evidence: DOC-0070 Registers & Logs; RPT-0060 Investment Product Strategy Report; reports.netcapital.mn upload log', '2026-09-21', 'NOT_STARTED');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('1ca5f186-8e35-5b85-90aa-e0b87202c671', '7fdf8f6f-00f4-523c-8501-f9f88ceae74d', 'KR2', 'Хариуцсан тайлантай холбоотой батлагдсан өөрчлөлтийн санал (change proposal)-ын хэрэгжилтийг \[0%→100%\] болгож 2026-09-28-ны дотор хангана.', 'Хариуцсан тайлан бүрийн document/process gap analysis хийж, шаардлагатай өөрчлөлтийн санал (change proposal)-ыг боловсруулж, СГУГ болон холбогдох нэгжтэй review хийлгэнэ. Review-ийн тайлбарыг тусган батлагдсан change proposal-уудын хэрэгжилтийн хуваарийн драфт гаргаж, СГУГ болон холбогдох нэгжийн захиралд ахин хянуулна. Батлагдсан proposal болон хэрэгжилтийн хяналтын баримтыг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгнө.    Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш):  • Change proposal тоо: тайлан бүрт ≥1  • Холбогдох нэгжийн хүлээн авалт: 100%', 30.0,
  '0%→100%\', 'Биелсэн гэж үзэх нөхцөл:  Хариуцсан тайлантай холбоотой бүх батлагдсан change proposal хэрэгжиж, ХОБПХГ-ийн газрын захирлаар хянагдсан байна.    Тооцох аргачлал:  Томьёо: Change Implementation Rate = (Хэрэгжсэн change proposal / Нийт батлагдсан proposal) × 100%    Шаталсан үнэлгээ:  100%: Бүх батлагдсан proposal хэрэгжсэн.  50%: 50%–99% proposal хэрэгжсэн.  0%: 50%-аас доош proposal хэрэгжсэн, эсвэл evidence дутуу.    Evidence: DOC-0035 Policy & Standard & Procedure Set; DOC-0070 Registers & Logs; Change proposal log', '2026-09-28', 'NOT_STARTED');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('f7bd33b8-0e50-5f5b-8816-bac443451a6a', '7fdf8f6f-00f4-523c-8501-f9f88ceae74d', 'KR3', 'C-Level-ийн хариуцсан event/committee/OKR schedule-ийн нэгдсэн календарийн хамрагдалтыг \[0%→100%\] болгож 2026-09-30-ны дотор хангана.', 'C-Level-ийн Q3-д хариуцсан event, committee болон OKR schedule-ийг цуглуулж, нэгдсэн календарийн template болон action tracker-ийг боловсруулж, C-Level хариуцагчид болон СГУГ-тай review хийлгэнэ. Review-ийн тайлбарыг тусган Q3-ийн нэгдсэн календарийн драфт болон action list гаргаж, C-Level-ийн захиралд ахин хянуулна. Баталгаажсан нэгдсэн календарийг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгч, Q3-ийн туршид action closure-ыг долоо хоног тутам хянана.    Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш):  • Action closure rate: 100%  • Календарийн шинэчлэлт давтамж: долоо хоног тутам', 20.0,
  '0%→100%\', 'Биелсэн гэж үзэх нөхцөл:  C-Level-ийн Q3-д товлогдсон event/committee/OKR schedule-ийн 100% нэгдсэн календарьт бүртгэгдэж, ХОБПХГ-ийн газрын захирлаар хянагдсан байна.    Тооцох аргачлал:  Томьёо: Calendar Coverage = (Нэгдсэн календарьт бүртгэгдсэн event тоо / Нийт товлогдсон event тоо) × 100%    Шаталсан үнэлгээ:  100%: Бүх event/schedule нэгдсэн календарьт бүртгэгдсэн.  50%: 50%–99% event бүртгэгдсэн.  0%: 50%-аас доош event бүртгэгдсэн, эсвэл evidence дутуу.    Evidence: DOC-0103 Management Pack; DOC-0070 Registers & Logs; C-Level calendar log', '2026-09-30', 'NOT_STARTED');

insert into key_results (id, objective_id, kr_code, title, description, weight,
  target_description, measurement_method, deadline, status)
values ('7386df7c-8f00-5d3a-8d3c-5ee7109f789e', '7fdf8f6f-00f4-523c-8501-f9f88ceae74d', 'KR4', 'Хариуцсан нэгжийн ажилтнуудын Claude сургалтын хамрагдалтыг \[0%→≥95%\] болгож 2026-09-30-ны дотор хангана.', 'Хариуцсан нэгжийн ажилтнуудад зориулан Claude суурь болон role-based сургалтын агуулга, хуваарь болон хамрагдуулах ажилтнуудын жагсаалтыг боловсруулж, СГУГ болон ХОБПХГ-ийн захиралтай review хийлгэнэ. Review-ийн тайлбарыг тусган сургалтын хөтөлбөр болон хамрагдалт хянах механизмын драфт гаргаж, СГУГ-д ахин хянуулна. Сургалтын дүн болон хамрагдалтын тайланг ХОБПХГ-ийн газрын захиралд хүлээлгэж өгнө.    Secondary indicators (харах зориулалттай, үнэлгээний гол шалгуур биш):  • Сургалт дуусгасан ажилтны тоо: нийт ≥95%  • Post-assessment дүн: ≥70%', 20.0,
  '0%→≥95%\', 'Биелсэн гэж үзэх нөхцөл:  Хариуцсан нэгжийн нийт ажилтны 95% буюу дээш нь Claude сургалтад хамрагдаж дуусгасан, ХОБПХГ-ийн газрын захирлаар хянагдсан байна.    Тооцох аргачлал:  Томьёо: Training Completion Rate = (Сургалт дуусгасан ажилтны тоо / Нийт ажилтны тоо) × 100%    Шаталсан үнэлгээ:  100%: ≥95% ажилтан сургалтад хамрагдаж дуусгасан.  50%: 70%–94.9% ажилтан хамрагдсан.  0%: 70%-аас доош ажилтан хамрагдсан, эсвэл evidence дутуу.    Evidence: DOC-0117 Experiment Registry; DOC-0070 Registers & Logs; Сургалтын бүртгэл болон attendance log', '2026-09-30', 'NOT_STARTED');

insert into work_items (id, key_result_id, owner_id, department_id, quarter_id, work_code,
  title, work_type, priority, definition_of_done, deadline, status, reviewer_id, approver_id,
  implementation_required, validation_required, created_by)
values ('df4f3d96-0992-5ad0-a5c0-3c615fd72857', 'f8a9166f-cb3b-5668-a310-056b749d77ef', 'e0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'IPPDD-2026Q3-W001',
  'Данс нээлтийн end-to-end процессын нэгдсэн стандарт багц (5 бүрэлдэхүүн)', 'PROCESS', 'CRITICAL', 'Process map, дүрэм, журам, RACI, control checklist — 5 бүрэлдэхүүн бүгд боловсрогдож, ХОБПХГ-ийн газрын захирлаар хянагдаж батлагдсан байна (Documentation Readiness 5/5).', '2026-08-24', 'IN_PROGRESS', 'e0000000-0000-4000-8000-000000000003', 'e0000000-0000-4000-8000-000000000001',
  false, false, 'e0000000-0000-4000-8000-000000000002');

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('263e2a2f-0dfa-5b90-95f4-5723303c0777', 'df4f3d96-0992-5ad0-a5c0-3c615fd72857', 'Process Map', true, 1);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('bd122ede-24ae-5546-b91c-a76a1c09883e', 'df4f3d96-0992-5ad0-a5c0-3c615fd72857', 'Дүрэм', true, 2);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('530b5002-b5cc-5e13-b915-7ccc6e11c018', 'df4f3d96-0992-5ad0-a5c0-3c615fd72857', 'Журам', true, 3);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('680f53af-d3c7-5ee8-af71-a35e8b637d70', 'df4f3d96-0992-5ad0-a5c0-3c615fd72857', 'RACI', true, 4);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('a40f7781-dd9c-5180-86e6-037bb66ac87f', 'df4f3d96-0992-5ad0-a5c0-3c615fd72857', 'Control Checklist', true, 5);

insert into work_items (id, key_result_id, owner_id, department_id, quarter_id, work_code,
  title, work_type, priority, definition_of_done, deadline, status, reviewer_id, approver_id,
  implementation_required, validation_required, created_by)
values ('d4198448-2c77-5bf9-82c3-2882c704a31d', '2de7ea1d-c703-5315-be44-b77f73d104d7', 'e0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'IPPDD-2026Q3-W002',
  'Харилцагчийн бэлгийн зарцуулалтын нотлох баримтын 3 баримт (checklist + стандарт + журам)', 'STANDARD', 'HIGH', '3 баримт бүгд боловсрогдож, ХОБПХГ-ийн газрын захирлаар хянагдаж батлагдсан байна.', '2026-08-23', 'IN_PROGRESS', 'e0000000-0000-4000-8000-000000000003', 'e0000000-0000-4000-8000-000000000001',
  false, false, 'e0000000-0000-4000-8000-000000000002');

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('befa03bc-0da8-5fb0-86ea-985701ffb442', 'd4198448-2c77-5bf9-82c3-2882c704a31d', 'Checklist', true, 1);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('1bfa747c-7eb3-5d11-9ea0-4d85bb97b4ac', 'd4198448-2c77-5bf9-82c3-2882c704a31d', 'Стандарт', true, 2);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('95a0c156-0b6e-57ec-92e9-58818098a79f', 'd4198448-2c77-5bf9-82c3-2882c704a31d', 'Журам', true, 3);

insert into work_items (id, key_result_id, owner_id, department_id, quarter_id, work_code,
  title, work_type, priority, definition_of_done, deadline, status, reviewer_id, approver_id,
  implementation_required, validation_required, created_by)
values ('bc81c57b-edba-5185-8e6a-a1dfb96a13c0', '8bc1ffe8-d36d-5bed-b794-97b5f0fed5a8', 'e0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'IPPDD-2026Q3-W003',
  'Claude автоматжуулалт — бэлгийн хяналтын 1 domain (coverage ≥80%)', 'AI_AGENT', 'HIGH', 'Сонгосон domain-д автоматжуулалтын process coverage ≥80%, тест давсан, хүний acceptance болон deployment/use evidence бүрдсэн байна.', '2026-09-06', 'IN_PROGRESS', 'e0000000-0000-4000-8000-000000000003', 'e0000000-0000-4000-8000-000000000001',
  true, true, 'e0000000-0000-4000-8000-000000000002');

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('b98b371e-bb33-52c2-9ab4-6fba005655e3', 'bc81c57b-edba-5185-8e6a-a1dfb96a13c0', 'Hypothesis / experiment design', true, 1);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('42104044-fc7c-5c9d-8aa4-2aa283bf0c95', 'bc81c57b-edba-5185-8e6a-a1dfb96a13c0', 'Test case багц', true, 2);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('054ec820-909f-5be6-99cf-255a2f606d92', 'bc81c57b-edba-5185-8e6a-a1dfb96a13c0', 'Pilot тайлан', true, 3);

insert into metric_validations (id, key_result_id, work_item_id, metric_name,
  target_operator, target_value, unit, validation_status)
values ('157c9162-6c0a-507f-893a-12f95fc925fa', '8bc1ffe8-d36d-5bed-b794-97b5f0fed5a8', 'bc81c57b-edba-5185-8e6a-a1dfb96a13c0', 'Process Coverage', 'GTE', 80, '%', 'PENDING');

insert into work_items (id, key_result_id, owner_id, department_id, quarter_id, work_code,
  title, work_type, priority, definition_of_done, deadline, status, reviewer_id, approver_id,
  implementation_required, validation_required, created_by)
values ('e1cd7bb4-f068-500f-8e5f-3bf3d9276ddf', '7386df7c-8f00-5d3a-8d3c-5ee7109f789e', 'e0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'IPPDD-2026Q3-W004',
  'Claude сургалт — харьяа нэгжийн ажилтнуудын хамрагдалт ≥95%', 'TRAINING', 'MEDIUM', 'Нийт ажилтны ≥95% сургалтад хамрагдаж дуусгасан, хамрагдалтын тайлан захирлаар хянагдсан.', '2026-09-30', 'IN_PROGRESS', 'e0000000-0000-4000-8000-000000000003', 'e0000000-0000-4000-8000-000000000001',
  false, true, 'e0000000-0000-4000-8000-000000000002');

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('fcf75425-4aae-5f96-87ac-a016ec3f0191', 'e1cd7bb4-f068-500f-8e5f-3bf3d9276ddf', 'Сургалтын хөтөлбөр', true, 1);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('f3d68967-7bdc-5a83-998a-93625522dd3c', 'e1cd7bb4-f068-500f-8e5f-3bf3d9276ddf', 'Хамрагдалтын тайлан', true, 2);

insert into metric_validations (id, key_result_id, work_item_id, metric_name,
  target_operator, target_value, unit, validation_status)
values ('d9f14894-2b99-5972-93e7-523dacb9f122', '7386df7c-8f00-5d3a-8d3c-5ee7109f789e', 'e1cd7bb4-f068-500f-8e5f-3bf3d9276ddf', 'Training Completion Rate', 'GTE', 95, '%', 'PENDING');

insert into work_items (id, key_result_id, owner_id, department_id, quarter_id, work_code,
  title, work_type, priority, definition_of_done, deadline, status, reviewer_id, approver_id,
  implementation_required, validation_required, created_by)
values ('8c08fc98-fb15-51f5-b7f3-f6d605924747', '329690bb-2c3a-5edd-a49c-855ccc95d788', 'e0000000-0000-4000-8000-000000000002', 'd0000000-0000-4000-8000-000000000001', 'a0000000-0000-4000-8000-000000000001', 'IPPDD-2026Q3-W005',
  'Weekly CPI review cadence — 13 хуралдааны гүйцэтгэл', 'KPI', 'MEDIUM', 'Q3-ийн 13 weekly CPI review бүгд явагдаж, процесс тус бүрийн ≥5 KPI метрик хэмжигдсэн.', '2026-09-16', 'IN_PROGRESS', 'e0000000-0000-4000-8000-000000000003', 'e0000000-0000-4000-8000-000000000001',
  false, true, 'e0000000-0000-4000-8000-000000000002');

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('faf9fa34-009f-545b-b77d-a47da0aa4d55', '8c08fc98-fb15-51f5-b7f3-f6d605924747', 'CPI review хуваарь ба агенда', true, 1);

insert into deliverable_requirements (id, work_item_id, name, required, sequence)
values ('d31d1e1e-4680-5758-b38c-f9b3f19dbb4a', '8c08fc98-fb15-51f5-b7f3-f6d605924747', 'KPI Dashboard загвар', true, 2);

insert into metric_validations (id, key_result_id, work_item_id, metric_name,
  target_operator, target_value, unit, validation_status)
values ('1a28771c-359d-5d20-aafb-27242109fb85', '329690bb-2c3a-5edd-a49c-855ccc95d788', '8c08fc98-fb15-51f5-b7f3-f6d605924747', 'CPI Review Completion', 'GTE', 13, 'хуралдаан', 'PENDING');

update key_results set status = 'IN_PROGRESS' where id = '2de7ea1d-c703-5315-be44-b77f73d104d7';

update key_results set status = 'IN_PROGRESS' where id = '329690bb-2c3a-5edd-a49c-855ccc95d788';

update key_results set status = 'IN_PROGRESS' where id = '7386df7c-8f00-5d3a-8d3c-5ee7109f789e';

update key_results set status = 'IN_PROGRESS' where id = '8bc1ffe8-d36d-5bed-b794-97b5f0fed5a8';

update key_results set status = 'IN_PROGRESS' where id = 'f8a9166f-cb3b-5668-a310-056b749d77ef';

commit;
